/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PdsAccordion {
    }
    interface PdsAvatar {
    }
    interface PdsBreadcrumb {
    }
    interface PdsButton {
    }
    interface PdsCalendar {
    }
    interface PdsCard {
    }
    interface PdsCheckbox {
    }
    interface PdsDropdown {
    }
    interface PdsFilter {
    }
    interface PdsInput {
    }
    interface PdsLoading {
    }
    interface PdsPagination {
    }
    interface PdsRadio {
    }
    interface PdsSearch {
    }
    interface PdsStepper {
    }
    interface PdsTab {
    }
    interface PdsTables {
    }
    interface PdsTags {
    }
    interface PdsTextarea {
    }
    interface PdsToast {
    }
    interface PdsToggle {
    }
    interface PdsTooltip {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPdsAccordionElement extends Components.PdsAccordion, HTMLStencilElement {
    }
    var HTMLPdsAccordionElement: {
        prototype: HTMLPdsAccordionElement;
        new (): HTMLPdsAccordionElement;
    };
    interface HTMLPdsAvatarElement extends Components.PdsAvatar, HTMLStencilElement {
    }
    var HTMLPdsAvatarElement: {
        prototype: HTMLPdsAvatarElement;
        new (): HTMLPdsAvatarElement;
    };
    interface HTMLPdsBreadcrumbElement extends Components.PdsBreadcrumb, HTMLStencilElement {
    }
    var HTMLPdsBreadcrumbElement: {
        prototype: HTMLPdsBreadcrumbElement;
        new (): HTMLPdsBreadcrumbElement;
    };
    interface HTMLPdsButtonElement extends Components.PdsButton, HTMLStencilElement {
    }
    var HTMLPdsButtonElement: {
        prototype: HTMLPdsButtonElement;
        new (): HTMLPdsButtonElement;
    };
    interface HTMLPdsCalendarElement extends Components.PdsCalendar, HTMLStencilElement {
    }
    var HTMLPdsCalendarElement: {
        prototype: HTMLPdsCalendarElement;
        new (): HTMLPdsCalendarElement;
    };
    interface HTMLPdsCardElement extends Components.PdsCard, HTMLStencilElement {
    }
    var HTMLPdsCardElement: {
        prototype: HTMLPdsCardElement;
        new (): HTMLPdsCardElement;
    };
    interface HTMLPdsCheckboxElement extends Components.PdsCheckbox, HTMLStencilElement {
    }
    var HTMLPdsCheckboxElement: {
        prototype: HTMLPdsCheckboxElement;
        new (): HTMLPdsCheckboxElement;
    };
    interface HTMLPdsDropdownElement extends Components.PdsDropdown, HTMLStencilElement {
    }
    var HTMLPdsDropdownElement: {
        prototype: HTMLPdsDropdownElement;
        new (): HTMLPdsDropdownElement;
    };
    interface HTMLPdsFilterElement extends Components.PdsFilter, HTMLStencilElement {
    }
    var HTMLPdsFilterElement: {
        prototype: HTMLPdsFilterElement;
        new (): HTMLPdsFilterElement;
    };
    interface HTMLPdsInputElement extends Components.PdsInput, HTMLStencilElement {
    }
    var HTMLPdsInputElement: {
        prototype: HTMLPdsInputElement;
        new (): HTMLPdsInputElement;
    };
    interface HTMLPdsLoadingElement extends Components.PdsLoading, HTMLStencilElement {
    }
    var HTMLPdsLoadingElement: {
        prototype: HTMLPdsLoadingElement;
        new (): HTMLPdsLoadingElement;
    };
    interface HTMLPdsPaginationElement extends Components.PdsPagination, HTMLStencilElement {
    }
    var HTMLPdsPaginationElement: {
        prototype: HTMLPdsPaginationElement;
        new (): HTMLPdsPaginationElement;
    };
    interface HTMLPdsRadioElement extends Components.PdsRadio, HTMLStencilElement {
    }
    var HTMLPdsRadioElement: {
        prototype: HTMLPdsRadioElement;
        new (): HTMLPdsRadioElement;
    };
    interface HTMLPdsSearchElement extends Components.PdsSearch, HTMLStencilElement {
    }
    var HTMLPdsSearchElement: {
        prototype: HTMLPdsSearchElement;
        new (): HTMLPdsSearchElement;
    };
    interface HTMLPdsStepperElement extends Components.PdsStepper, HTMLStencilElement {
    }
    var HTMLPdsStepperElement: {
        prototype: HTMLPdsStepperElement;
        new (): HTMLPdsStepperElement;
    };
    interface HTMLPdsTabElement extends Components.PdsTab, HTMLStencilElement {
    }
    var HTMLPdsTabElement: {
        prototype: HTMLPdsTabElement;
        new (): HTMLPdsTabElement;
    };
    interface HTMLPdsTablesElement extends Components.PdsTables, HTMLStencilElement {
    }
    var HTMLPdsTablesElement: {
        prototype: HTMLPdsTablesElement;
        new (): HTMLPdsTablesElement;
    };
    interface HTMLPdsTagsElement extends Components.PdsTags, HTMLStencilElement {
    }
    var HTMLPdsTagsElement: {
        prototype: HTMLPdsTagsElement;
        new (): HTMLPdsTagsElement;
    };
    interface HTMLPdsTextareaElement extends Components.PdsTextarea, HTMLStencilElement {
    }
    var HTMLPdsTextareaElement: {
        prototype: HTMLPdsTextareaElement;
        new (): HTMLPdsTextareaElement;
    };
    interface HTMLPdsToastElement extends Components.PdsToast, HTMLStencilElement {
    }
    var HTMLPdsToastElement: {
        prototype: HTMLPdsToastElement;
        new (): HTMLPdsToastElement;
    };
    interface HTMLPdsToggleElement extends Components.PdsToggle, HTMLStencilElement {
    }
    var HTMLPdsToggleElement: {
        prototype: HTMLPdsToggleElement;
        new (): HTMLPdsToggleElement;
    };
    interface HTMLPdsTooltipElement extends Components.PdsTooltip, HTMLStencilElement {
    }
    var HTMLPdsTooltipElement: {
        prototype: HTMLPdsTooltipElement;
        new (): HTMLPdsTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pds-accordion": HTMLPdsAccordionElement;
        "pds-avatar": HTMLPdsAvatarElement;
        "pds-breadcrumb": HTMLPdsBreadcrumbElement;
        "pds-button": HTMLPdsButtonElement;
        "pds-calendar": HTMLPdsCalendarElement;
        "pds-card": HTMLPdsCardElement;
        "pds-checkbox": HTMLPdsCheckboxElement;
        "pds-dropdown": HTMLPdsDropdownElement;
        "pds-filter": HTMLPdsFilterElement;
        "pds-input": HTMLPdsInputElement;
        "pds-loading": HTMLPdsLoadingElement;
        "pds-pagination": HTMLPdsPaginationElement;
        "pds-radio": HTMLPdsRadioElement;
        "pds-search": HTMLPdsSearchElement;
        "pds-stepper": HTMLPdsStepperElement;
        "pds-tab": HTMLPdsTabElement;
        "pds-tables": HTMLPdsTablesElement;
        "pds-tags": HTMLPdsTagsElement;
        "pds-textarea": HTMLPdsTextareaElement;
        "pds-toast": HTMLPdsToastElement;
        "pds-toggle": HTMLPdsToggleElement;
        "pds-tooltip": HTMLPdsTooltipElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PdsAccordion {
    }
    interface PdsAvatar {
    }
    interface PdsBreadcrumb {
    }
    interface PdsButton {
    }
    interface PdsCalendar {
    }
    interface PdsCard {
    }
    interface PdsCheckbox {
    }
    interface PdsDropdown {
    }
    interface PdsFilter {
    }
    interface PdsInput {
    }
    interface PdsLoading {
    }
    interface PdsPagination {
    }
    interface PdsRadio {
    }
    interface PdsSearch {
    }
    interface PdsStepper {
    }
    interface PdsTab {
    }
    interface PdsTables {
    }
    interface PdsTags {
    }
    interface PdsTextarea {
    }
    interface PdsToast {
    }
    interface PdsToggle {
    }
    interface PdsTooltip {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pds-accordion": PdsAccordion;
        "pds-avatar": PdsAvatar;
        "pds-breadcrumb": PdsBreadcrumb;
        "pds-button": PdsButton;
        "pds-calendar": PdsCalendar;
        "pds-card": PdsCard;
        "pds-checkbox": PdsCheckbox;
        "pds-dropdown": PdsDropdown;
        "pds-filter": PdsFilter;
        "pds-input": PdsInput;
        "pds-loading": PdsLoading;
        "pds-pagination": PdsPagination;
        "pds-radio": PdsRadio;
        "pds-search": PdsSearch;
        "pds-stepper": PdsStepper;
        "pds-tab": PdsTab;
        "pds-tables": PdsTables;
        "pds-tags": PdsTags;
        "pds-textarea": PdsTextarea;
        "pds-toast": PdsToast;
        "pds-toggle": PdsToggle;
        "pds-tooltip": PdsTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pds-accordion": LocalJSX.PdsAccordion & JSXBase.HTMLAttributes<HTMLPdsAccordionElement>;
            "pds-avatar": LocalJSX.PdsAvatar & JSXBase.HTMLAttributes<HTMLPdsAvatarElement>;
            "pds-breadcrumb": LocalJSX.PdsBreadcrumb & JSXBase.HTMLAttributes<HTMLPdsBreadcrumbElement>;
            "pds-button": LocalJSX.PdsButton & JSXBase.HTMLAttributes<HTMLPdsButtonElement>;
            "pds-calendar": LocalJSX.PdsCalendar & JSXBase.HTMLAttributes<HTMLPdsCalendarElement>;
            "pds-card": LocalJSX.PdsCard & JSXBase.HTMLAttributes<HTMLPdsCardElement>;
            "pds-checkbox": LocalJSX.PdsCheckbox & JSXBase.HTMLAttributes<HTMLPdsCheckboxElement>;
            "pds-dropdown": LocalJSX.PdsDropdown & JSXBase.HTMLAttributes<HTMLPdsDropdownElement>;
            "pds-filter": LocalJSX.PdsFilter & JSXBase.HTMLAttributes<HTMLPdsFilterElement>;
            "pds-input": LocalJSX.PdsInput & JSXBase.HTMLAttributes<HTMLPdsInputElement>;
            "pds-loading": LocalJSX.PdsLoading & JSXBase.HTMLAttributes<HTMLPdsLoadingElement>;
            "pds-pagination": LocalJSX.PdsPagination & JSXBase.HTMLAttributes<HTMLPdsPaginationElement>;
            "pds-radio": LocalJSX.PdsRadio & JSXBase.HTMLAttributes<HTMLPdsRadioElement>;
            "pds-search": LocalJSX.PdsSearch & JSXBase.HTMLAttributes<HTMLPdsSearchElement>;
            "pds-stepper": LocalJSX.PdsStepper & JSXBase.HTMLAttributes<HTMLPdsStepperElement>;
            "pds-tab": LocalJSX.PdsTab & JSXBase.HTMLAttributes<HTMLPdsTabElement>;
            "pds-tables": LocalJSX.PdsTables & JSXBase.HTMLAttributes<HTMLPdsTablesElement>;
            "pds-tags": LocalJSX.PdsTags & JSXBase.HTMLAttributes<HTMLPdsTagsElement>;
            "pds-textarea": LocalJSX.PdsTextarea & JSXBase.HTMLAttributes<HTMLPdsTextareaElement>;
            "pds-toast": LocalJSX.PdsToast & JSXBase.HTMLAttributes<HTMLPdsToastElement>;
            "pds-toggle": LocalJSX.PdsToggle & JSXBase.HTMLAttributes<HTMLPdsToggleElement>;
            "pds-tooltip": LocalJSX.PdsTooltip & JSXBase.HTMLAttributes<HTMLPdsTooltipElement>;
        }
    }
}
